// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
/// 
//htha class principl fih parametre kol platform
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }
//hna kol may5ous firebase 
  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCi-UTQReIk0l5gA9ayDNgUrEIXWteDPXQ',
    appId: '1:857843523698:web:a8cd7566edb367eee6e2eb',
    messagingSenderId: '857843523698',
    projectId: 'pfes-5bb45',
    authDomain: 'pfes-5bb45.firebaseapp.com',
    storageBucket: 'pfes-5bb45.firebasestorage.app',
    measurementId: 'G-46NQ77M3V2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAqwrEkQOfE_2J2HLOTyvC92dqXsEX6-mQ',
    appId: '1:857843523698:android:c0b9c6eaa59d0aebe6e2eb',
    messagingSenderId: '857843523698',
    projectId: 'pfes-5bb45',
    storageBucket: 'pfes-5bb45.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBAaeu8JcmsF2R_M1c9DeRY0a-by7NWORI',
    appId: '1:857843523698:ios:dca60ecbe2acf166e6e2eb',
    messagingSenderId: '857843523698',
    projectId: 'pfes-5bb45',
    storageBucket: 'pfes-5bb45.firebasestorage.app',
    iosBundleId: 'com.example.pfes',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBAaeu8JcmsF2R_M1c9DeRY0a-by7NWORI',
    appId: '1:857843523698:ios:dca60ecbe2acf166e6e2eb',
    messagingSenderId: '857843523698',
    projectId: 'pfes-5bb45',
    storageBucket: 'pfes-5bb45.firebasestorage.app',
    iosBundleId: 'com.example.pfes',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCi-UTQReIk0l5gA9ayDNgUrEIXWteDPXQ',
    appId: '1:857843523698:web:2005af442e1d5913e6e2eb',
    messagingSenderId: '857843523698',
    projectId: 'pfes-5bb45',
    authDomain: 'pfes-5bb45.firebaseapp.com',
    storageBucket: 'pfes-5bb45.firebasestorage.app',
    measurementId: 'G-23WJ6E1PRV',
  );

}